### ISSUE TITLE
Activity/Sleep mixup

### ISSUE THREAD

**Issue by jonathandmoore** [praveendath92/fitbit-googlefit#11]
First, this is a great achievement.  I followed the instructions and got the app working within a few minutes.  My Fitbit data is >1yr  so I set it to synchronise all.  Every 20days worth of data the Fitbit API would pause for 50 minutes, due to their rate limit policy.  Less than 24 hours later all my data was synced.

The logs of heart rate, weight, calories, distance and steps look right.  The logs of individual activities (walking in my case mostly) and sleep are inconsistent.  Some activities are synced correctly, sometimes the activity is named 'Sleep' but has steps listed, sometimes the activity is listed as lasting 23hr59min and includes the whole day's steps.

I'm very happy to clear Google Fit and re-sync if you have any fixes in the pipeline. If I can help debug, let me know.

I took the code on 27th Aug, but I can't find a version. Can it have a -v option?

**Comment by praveendath92** [comment]
@jonathandmoore , Thanks for the elaborate feedback. I use the same tool to export my data so, I certainly would fix any known issues.

With that said, the sleep issue is actually coming from the Google Fit Web interface - Google Fit takes sleep logging as an activity. The tool here actually tags your Fitbit sleep log perfectly as a Sleep activity - including [3 different levels of sleep within your sleep log](https://github.com/praveendath92/fitbit-googlefit/blob/master/convertors.py#L204-L211).

Google Fit web interface doesn't support adding or tagging an activity as sleep so, my guess is, when it sees any activity that it doesn't support, it shows up as "Walking" - the underlying tags however are correct. You can verify this by noticing that the sleep activities are not contributed to your active time even though they are shown as "Walking".

**Comment by praveendath92** [comment]
"sometimes the activity is listed as lasting 23hr59min and includes the whole day's steps." - if you can give me some more information, I will debug and try to fix this. 

I will add a ```-v``` option in my next commit.

**Comment by praveendath92** [comment]
@jonathandmoore , I just debugged the "23hr59min" issue. Unfortunately, I don't see any bug in the tool itself. I verified that the start and end times sent to Google Fit API are correct. I will wait a couple of days and see if Google Fit web interface corrects itself.

**Comment by matt-boyd-pdx** [comment]
@praveendath92, The 23 hr 59 min issue is coming from the conversion from FitBit to Google formats. The sleep data points are in sequenced time stamps (no date). The conversion applies the FitBit date (starting day) to all of the times in the sequence. When the times roll past midnight the conversion keeps the same date instead of rolling forward. I submitted a pull request that addresses the issue.

**Comment by matt-boyd-pdx** [comment]
One more pull request to fix sleep duration and make Google Fit report sleep duration accurately.
