### ISSUE TITLE
Sync a on a Pi with Raspbian

### ISSUE THREAD

**Issue by fabiobruna** [praveendath92/fitbit-googlefit#18]
Not a real issue (for me), works on my mac (like a charm, great work) but just to inform you, on my raspberry pi got this message:

```
$ python3 app.py -s "2 days ago" -e tomorrow
Traceback (most recent call last):
  File "app.py", line 17, in <module>
    from helpers import *
  File "/home/pi/fitbit-googlefit/helpers.py", line 8, in <module>
    import fitbit
ImportError: No module named fitbit
```
Totally no experience w python, so maybe it's a small thing.

**Comment by praveendath92** [comment]
@fabiobruna , I think you forgot to [install dependencies](https://github.com/praveendath92/fitbit-googlefit#1-install-dependencies) on your Pi.

**Comment by fabiobruna** [comment]
Ah, my bad, should have checked the install output first.. 

```
 Running setup.py egg_info for package mock
    mock requires setuptools>=17.1. Aborting installation
    Complete output from command python setup.py egg_info:
    mock requires setuptools>=17.1. Aborting installation
```

Thanks.

**Comment by praveendath92** [comment]
This error is new. I hope you sorted it out. If so, let me know and I will close the issue.

**Comment by fabiobruna** [comment]
I'll try to solve it an get back with info.

**Comment by fabiobruna** [comment]
@praveendath92 Solved it. Problem ~~is~~ was the Python version on my Pi. That's 3.2 on a standard Rasbian Wheezy installation. Did an upgrade to 3.5 with these great instructions => http://bohdan-danishevsky.blogspot.nl/2015/10/building-python-35-on-raspberry-pi-2.html

Works like a charm now. Much more convenient to schedule with my Pi.

**Comment by praveendath92** [comment]
@fabiobruna , glad you could fix it. Thanks for sharing the fix here 😄
