### ISSUE TITLE
Unable to authorise Fitbit

### ISSUE THREAD

**Issue by resolS** [praveendath92/fitbit-googlefit#19]
I try and authorise my Fitbit account, but it keeps on failing. I get the below error
I've tried recreating an application on Fitbit, but it doesn't work.
I've followed the youtube video as well. Please help. :)

[25/Jan/2017:21:24:33] ENGINE Started monitor thread 'Autoreloader'.
[25/Jan/2017:21:24:33] ENGINE Started monitor thread '_TimeoutMonitor'.
[25/Jan/2017:21:24:33] ENGINE Serving on http://127.0.0.1:8080
[25/Jan/2017:21:24:33] ENGINE Bus STARTED
127.0.0.1 - - [25/Jan/2017:21:25:35] "GET /?code=925c812757aa2c1d1kjjgkdb677d3f414bbc404e0&state=L4tw7ZXzkhmmms2VoiivVvB8zphB HTTP/1.1" 200 122 "" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393"
[25/Jan/2017:21:25:36] ENGINE Bus STOPPING
[25/Jan/2017:21:25:45] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('127.0.0.1', 8080)) shut down
[25/Jan/2017:21:25:45] ENGINE Stopped thread 'Autoreloader'.
[25/Jan/2017:21:25:45] ENGINE Stopped thread '_TimeoutMonitor'.
[25/Jan/2017:21:25:45] ENGINE Bus STOPPED
[25/Jan/2017:21:25:45] ENGINE Bus EXITING
[25/Jan/2017:21:25:45] ENGINE Bus EXITED
[25/Jan/2017:21:25:45] ENGINE Waiting for child threads to terminate...
Traceback (most recent call last):
  File "auth_fitbit.py", line 109, in <module>
    main()
  File "auth_fitbit.py", line 104, in main
    access_token=server.oauth.token['access_token'],
AttributeError: 'FitbitOauth2Client' object has no attribute 'token'

**Comment by resolS** [comment]
I think this 
access_token=server.oauth.token['access_token'],
refresh_token=server.oauth.token['refresh_token']


should read like this

access_token=server.oauth.token.**session**['access_token']
refresh_token=server.oauth.token.**session**['refresh_token']

in both auth_fitbit.py and remote.py

**Comment by praveendath92** [comment]
@resolS , At first I wondered if something may have changed in the authentication process but I just tried authenticating with the current version of the repo and it works. It's probably your browser? Which browser are you using to authenticate?

**Comment by resolS** [comment]
I tried using Google Chrome and Microsoft Edge, same issue on both.
I'm running Windows 10.

I went to the original version of the file you used and just took the info I obtained from that and manually added it into the JSON
https://github.com/orcasgit/python-fitbit/blob/master/gather_keys_oauth2.py

I then made the ".session" change in the remote.py file and it all works now :)

**Comment by praveendath92** [comment]
Hmm. Strange that it works for me without any changes - I tested on Mac, Windows 10 (2 months ago) and Linux. Will see if the ".session" change would also work for me.

**Comment by praveendath92** [comment]
@resolS Thanks for pointing it out and also, coming up with a fix!

**Comment by resolS** [comment]
@praveendath92 Thanks for making this awesome tool!

**Comment by praveendath92** [comment]
@resolS , It looks like this is caused by an update in one of the dependencies. Since you are the one who noticed and fixed this issue, would you like to fix it and create a pull request? I can also fix this myself but I want to check with you first.

**Comment by resolS** [comment]
No, you go ahead :)
