### ISSUE TITLE
exception KeyError: 'activities-steps-intraday' when trying to sync

### ISSUE THREAD

**Issue by rickysarraf** [praveendath92/fitbit-googlefit#2]
While working on https://github.com/praveendath92/fitbit-googlefit/issues/1, the next gradual exception is got is:

```
rrs@learner:/var/tmp/lxc/fitbit-googlefit (master)$ python3 app.py 
------------------------------   2016-08-16  -------------------------
Traceback (most recent call last):
  File "app.py", line 107, in <module>
    main()
  File "app.py", line 77, in main
    remote.SyncFitbitToGoogleFit(fitbitClient,googleClient,'steps',date_stamp,tzinfo)
  File "/media/SSHD/var/tmp/lxc/fitbit-googlefit/remote.py", line 112, in SyncFitbitToGoogleFit
    return SyncFitbitIntradayToGoogleFit(fitbitClient, googleClient, dataType, date_stamp, tzinfo)
  File "/media/SSHD/var/tmp/lxc/fitbit-googlefit/remote.py", line 143, in SyncFitbitIntradayToGoogleFit
    intraday_data = interday_raw[resp_id]['dataset']
KeyError: 'activities-steps-intraday'
2016-08-18 / 14:46:48 ♒♒♒  ☹  => 1  
```

**Comment by praveendath92** [comment]
Are you using the same account for Fitbit app registration and sync?

**Comment by rickysarraf** [comment]
I guess, yes. Because I've got just one Fitbit a/c and only 1 fitbit developer account.

**Comment by rickysarraf** [comment]
There is no key named intraday.

```
{'activities-steps': [{'value': '12567', 'dateTime': '2016-08-16'}]}
```

**Comment by praveendath92** [comment]
Thanks for giving a sample of the response. The error is because fitbit intraday data is not sent for your account. Fitbit website says that this data will be available if you request it from the same account you use for app registration.

**Comment by praveendath92** [comment]
Could you please double check about the account? I understand that most of us have only one Fitbit account. Just in case. If they are same, I would suggest requesting Fitbit support for intraday access.

**Comment by praveendath92** [comment]
I'm on the move right now. I will post a sample response from my account so you get an idea of how the response should look like. I'm sorry you had to go through these extra troubles but once done, I promise, you can see very precise date.

**Comment by rickysarraf** [comment]
No. THis one was broken on my part. I had created a fresh a/c today, and somehow ended up with type "Server" instead of "Personal".

**Comment by praveendath92** [comment]
I hope you could do sync now. I will work on issue #1 tonight.

**Comment by sum-it** [comment]
Same issue. If you have some error in the form while registering fitbit dev account "OAuth 2.0 Application Type" resets to Server.

**Comment by praveendath92** [comment]
The Application Type **must** be Personal.
