### ISSUE TITLE
Cant authorize on FitBit API

### ISSUE THREAD

**Issue by madsmash** [praveendath92/fitbit-googlefit#20]
Hello, 

I tried to follow all steps explained and I get this error when trying to run python3 auth_fitbit.py <user_id> <user_secret>

I get the following error after seeing the success message on the callback url:
[26/Jan/2017:17:40:15] ENGINE Bus EXITED
[26/Jan/2017:17:40:15] ENGINE Waiting for child threads to terminate...
Traceback (most recent call last):
  File "auth_fitbit.py", line 109, in <module>
    main()
  File "auth_fitbit.py", line 104, in main
    access_token=server.oauth.token['access_token'],
AttributeError: 'FitbitOauth2Client' object has no attribute 'token'

I guess some dependency has been updated and this doesn't work any more.

Thanks for the help

**Comment by praveendath92** [comment]
@madsmash , you are right. Last noticed with #19 but didn't realize it could be due to an updated dependency.
