### ISSUE TITLE
Steps wont show up on fit.google.com

### ISSUE THREAD

**Issue by MartinMeyer** [praveendath92/fitbit-googlefit#25]
First of all: I'm running your script on a Raspberry Pi.

I've used the workaround from #16 to login to fitbit and to login to google the `--noauth_local_webserver` flag.
For both I got the success-screen from http://localhost:8080/ and it seems that the sync was successful:

```------------------------------   2017-02-18  -------------------------
synced steps - 1440 data points
synced heart_rate - 0 data points

------------------------------   2017-02-19  -------------------------
synced steps - 1440 data points
synced heart_rate - 0 data points

------------------------------   2017-02-20  -------------------------
synced steps - 606 data points
synced heart_rate - 0 data points```

But when I login to https://fit.google.com I didn't see the steps on the dashboard.

I've tried it two times, with differenct Client-IDs/-secrets and it doesn't show up any steps/activities or any data on the google-fit dashboard.

I can't use the Google-Fit-App, so I have to use the web-version.

**Comment by praveendath92** [comment]
@MartinMeyer , Could you double check that you are using the same Google account in both cases? - authentication and web version.

**Comment by praveendath92** [comment]
Since I haven't heard back on this for a while, I will close this for now. Feel free to reopen if the problem persists.
