### ISSUE TITLE
Fitbit's "spinning" activity to GoogleFit's "ergometer" activity sync

### ISSUE THREAD

**Issue by unicorn855** [praveendath92/fitbit-googlefit#30]
Do you think it's possible to add fitbit's "spinning" activity and have it correspond to googleFit's "ergometer" activity? Unfortunately, I don't know the actual corresponding activity ID though.

**Comment by praveendath92** [comment]
@unicorn855, Thanks. I will lookup the ids.

**Comment by unicorn855** [comment]
@praveendath92, awesome, thank you :-) and now that I have an account, I'll go and star your repo ;-)

**Comment by praveendath92** [comment]
😄

**Comment by praveendath92** [comment]
Resolved in #59
