### ISSUE TITLE
odd data accumulation issue when syncing several times per day

### ISSUE THREAD

**Issue by unicorn855** [praveendath92/fitbit-googlefit#31]
I have noticed that google mixes up data and puts out nonsensical values when you sync the same day several times (to update it through the course of the day). Should I just sync once? I further noticed that when I manually delete an activity on google, sometimes it just doesn't seem to delete it or put a different activity in its place (maybe that's a caching problem on Google's side?)

**Comment by praveendath92** [comment]
Both are known issues. For this reason, I try to sync data for until the previous day only. I had the deleting problem many times too, I think Google Fit team should look into that IMO.

**Comment by unicorn855** [comment]
oh I see, I will adjust the config file accordingly then :) thanks
