### ISSUE TITLE
Feature: Add Fitbit sleep data to Google Fit

### ISSUE THREAD

**Issue by rickysarraf** [praveendath92/fitbit-googlefit#4]
Since this wasn't listed in your project, I thought of adding this here. It'd be nice to have the sleep data added to Google Fit.

As per the support page from Fit, it seems to support sleep data.
https://support.google.com/fit/?hl=en

**Comment by praveendath92** [comment]
I was planning to add it. But since there's no viewing for sleep data on the Google Fit app, I didn't finish it. 

However, I would love to have contributions. If you need any help adding support, let me know. I already looked at a viable path to do this. It may be little bit more effort to add it properly - light sleep, deep sleep and awake intervals.

**Comment by rickysarraf** [comment]
I'm surprised. I recollect having seen that data's representation in Google Fit, when I was using my Xiaomi Mi Band to sync to it. But Mi seems to have quietly dropped Fit integration recently, and Google Fit too doesn't seem to display the old synced data anymore.

I'll keep looking....

**Comment by praveendath92** [comment]
Doesn't display old data anymore ==> Mi delete the data before removing sync support! That's just plain unethical!

**Comment by rickysarraf** [comment]
Oh!! I wasn't aware of that. BTW, is github the preferred interface for communication? I don't really want to talk privately because most of the conversation could be useful to others too. So, I'll file one more bug now.

**Comment by praveendath92** [comment]
I prefer discussing useful stuff here for future reference to others. But if you want to discuss anything privately, you can email me. I tried deleting data added by a different Google Fit app and I couldn't. I noticed that Google Fit permits apps to read data added by other apps but modify requests must come from the app that added the data.
