### ISSUE TITLE
[Question] about browser authentication

### ISSUE THREAD

**Issue by lightmaster** [praveendath92/fitbit-googlefit#44]
I'm writing a way for `app.py` to check if the authentication files already exist, and if they don't, to run the authentication scripts that are necessary. My copy is running headless on a Digital Ocean server, so I haven't run the script with the browser authentication method yet. The browser method does pause while you log into fitbit/google, and then continues after it gets a response, correct? I know the headless method waits until you type in the redirect url, just want to make sure the browser method also waits so I know if I need to add a pause after running that script.

My ultimate goal is that you download this program and just run `app.py`. The first time its run, it installs itself, gives you a chance to edit the config file, then runs the authentication scripts if the resulting files don't already exist. On subsequent runs, `app.py` sees that its already installed, `config.ini` has already been edit (if user wanted it edited), and both authentication files already exist, so it skips over all that and runs like normal.

**Comment by praveendath92** [comment]
Yes, the browser method also pauses until the authentication is finished. I like the idea, let me know if you need any help. While you are at this, it would be nice if we can start the authentication when the access tokens expired - or that can be added as a feature later on.

**Comment by praveendath92** [comment]
Please be sure to test both headless and browser based authentications manually before sending your PR 😃

**Comment by lightmaster** [comment]
I was working on it at work last night and couldn't run python on my work computer, so I could only run it on my Digital Ocean server. Just successfully tested my latest commit on my Chromebook using both the browser and headless methods. Cron doesn't seem to work on my Chromebook (not surprising since its just a chroot on a system you shouldn't have shell access to period), so still need to pull the latest commit on my server to make sure the cron script will autorun successfully.
