### ISSUE TITLE
Instructions for creating Google project and credentials are not quite correct

### ISSUE THREAD

**Issue by jikamens** [praveendath92/fitbit-googlefit#55]
If you walk through the steps documented here for creating a Google project and credentials, you will see that they are no longer quite correct.

**Comment by praveendath92** [comment]
If you could make a PR correcting this, more than glad to review and accept it :)

**Comment by praveendath92** [comment]
They are not significantly different - user can easily figure out the differences. Open a PR if you think otherwise
