### ISSUE TITLE
NameError: name 'googleClient' is not defined

### ISSUE THREAD

**Issue by perdidohate** [praveendath92/fitbit-googlefit#6]
Good day, in first place thanks for this piece of software.

When i launch "python3 app.py -s 2016-08-15 -e 2016-08-21"

it returns this:

` File "/home/perdido/programmi/fitbit-googlefit-master/remote.py", line 102, in CreateGoogleFitDataSource
    dataSourceId=self.convertor.GetDataSourceId(dataType)).execute()
  File "/usr/local/lib/python3.5/dist-packages/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/googleapiclient/http.py", line 838, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 404 when requesting https://www.googleapis.com/fitness/v1/users/me/dataSources/raw%3Acom.google.step_count.delta%3A676930878379%3Afitbit%3Acharge-hr%3Aio.pkp.fbit-gfit?alt=json returned "DataSourceId not found: raw:com.google.step_count.delta:676930878379:fitbit:charge-hr:io.pkp.fbit-gfit">

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app.py", line 96, in <module>
    main()
  File "app.py", line 52, in main
    remote.CreateGoogleFitDataSource(dataType)
  File "/home/perdido/programmi/fitbit-googlefit-master/remote.py", line 107, in CreateGoogleFitDataSource
    googleClient.users().dataSources().create(
NameError: name 'googleClient' is not defined
`
I've got the two files correctly for the auth2 api usage, but i've just setup the google fit account.
i need to do something to inizialize? i've run through the setup, enable everything it asks me to enable and set up an objective, is it enough?
Because it seems a call to something that not exist related to google fit... but maybe i'm wrong

Thanks

**Comment by perdidohate** [comment]
probably a problem with authentication. I' ll try a little harder to solve this

**Comment by praveendath92** [comment]
@perdidohate , It was my mistake. I restructured the code a few commits ago and this part of the code was never tested from my account. Will push a fix in 5 mins.

**Comment by praveendath92** [comment]
@perdidohate , Try now!

**Comment by perdidohate** [comment]
it works perfectly!
Thank you very much for the quick fix

**Comment by praveendath92** [comment]
Glad it did! Please consider giving a **star** if you find it useful 😄
