### ISSUE TITLE
No activities found after $DATE

### ISSUE THREAD

**Issue by rickysarraf** [praveendath92/fitbit-googlefit#7]
I think the message here is misleading, because for sure it synced activities after the 19th ?

```
rrs@learner:~/.rrs-home/Community/fitbit-googlefit (master)$ ./cron.sh 
------------------------------   2016-08-19  -------------------------
synced steps
synced distance
synced heart_rate
synced weight
synced calories

------------------------------   2016-08-20  -------------------------
synced steps
synced distance
synced heart_rate
synced weight
synced calories

------------------------------   2016-08-21  -------------------------
synced steps
synced distance
synced heart_rate
synced weight
synced calories

------------------------------   2016-08-22  -------------------------
synced steps
synced distance
synced heart_rate
synced weight
synced calories

No activities found after 2016-08-19

2016-08-22 / 18:27:59 ♒♒♒  ☺  
```

**Comment by praveendath92** [comment]
The message appears when Fitbit API returns no activities on or after 19th. So, it doesn't sync have any activities to sync to Google Fit.

**Comment by rickysarraf** [comment]
The messaging shows does not give that impression. Also, I think my phone is synced with fitbit up till yesterday. Let me grab a screenshot.

**Comment by rickysarraf** [comment]
![screenshot_2016-08-22-19-06-05-203_com fitbit fitbitmobile](https://cloud.githubusercontent.com/assets/65480/17857450/668cef3c-689f-11e6-9a7e-041e15f8b6ca.png)

**Comment by praveendath92** [comment]
@rickysarraf How about if I change the message to "No Fitbit activities logged since %date%". I think it's just the wording. The script itself doesn't have any issues in syncing activities - if they are returned by Fitbit API.

I have been using this as a cron job for 3 days now without any issues.

**Comment by rickysarraf** [comment]
Yes. I think that'd be better. Because, at least then, it'd mean something to do with the Fitbit api, which is giving a different dataset than what Fitbit's phone app is claiming.

**Comment by rickysarraf** [comment]
@praveendath92  I'm sharing further details here as I don't want to open another issue.

```
rrs@learner:~/.rrs-home/Community/fitbit-googlefit (master)$ ./cron.sh 
------------------------------   2016-08-16  -------------------------
synced steps
synced distance
synced heart_rate
synced weight
synced calories

------------------------------   2016-08-17  -------------------------
synced steps
synced distance
synced heart_rate
synced weight
synced calories

------------------------------   2016-08-18  -------------------------
synced steps
synced distance
synced heart_rate
synced weight
synced calories

------------------------------   2016-08-19  -------------------------
synced steps
synced distance
synced heart_rate
synced weight
synced calories

------------------------------   2016-08-20  -------------------------
synced steps
synced distance
synced heart_rate
synced weight
synced calories

------------------------------   2016-08-21  -------------------------
synced steps
synced distance
synced heart_rate
synced weight
synced calories

------------------------------   2016-08-22  -------------------------
synced steps
synced distance
synced heart_rate
synced weight
synced calories

------------------------------   2016-08-23  -------------------------
synced steps
synced distance
synced heart_rate
synced weight
synced calories

------------------------------   2016-08-24  -------------------------
synced steps
synced distance
synced heart_rate
synced weight
synced calories

Synced 4 activities : 2016-08-17 -- 2016-08-18

2016-08-24 / 15:31:50 ♒♒♒  ☺  
```


How should this reporting be interpreted ? I manually added 2016-08-16 as the start date, and end date is "tomorrow".

**Comment by praveendath92** [comment]
Synced 4 activities that are logged in the interval (2016-08-17 -- 2016-08-18). No activities found after 18th. Take a look at this [relevant code block](https://github.com/praveendath92/fitbit-googlefit/blob/master/remote.py#L230-L238) if you want to dig al little deeper.

**Comment by rickysarraf** [comment]
```
# Write a day of fitbit data to Google fit
self.WriteToGoogleFit(dataSourceId, googlePoints)
print("synced {}".format(dataType))
```

This gives the impression that data is being synced, which actually is being overwritten in Google Fit.

If so, shouldn't this just be suppressed ? Only show them in verbose mode.
This gives the impression that data is being synced, where as the summary at the end contradicts it.

**Comment by praveendath92** [comment]
I don't follow the contradiction part. Data points are added / updated. In either case, it is shown as "synced".

**Comment by praveendath92** [comment]
@rickysarraf , I think the latest changes addresses some of these concerns. The new activity sync log would like:

```
....

------------------------------   2016-08-26  -------------------------
synced steps
synced distance
synced heart_rate
synced weight
synced body_fat
synced calories

Synced 5 activities between : 2016-08-23 -- 2016-08-24
No more Fitbit activities to sync after 2016-08-24
```

**Comment by rickysarraf** [comment]
Thanks for fixing the other bugs. :-)

This is what I got with today's changes.

```
rrs@learner:~/.rrs-home/Community/fitbit-googlefit (master)$ ./cron.sh 
------------------------------   2016-08-23  -------------------------
synced steps
synced distance
synced heart_rate
synced weight
synced body_fat
synced calories

------------------------------   2016-08-24  -------------------------
synced steps
synced distance
synced heart_rate
synced weight
synced body_fat
synced calories

------------------------------   2016-08-25  -------------------------
synced steps
synced distance
synced heart_rate
synced weight
synced body_fat
synced calories

------------------------------   2016-08-26  -------------------------
synced steps
synced distance
synced heart_rate
synced weight
synced body_fat
synced calories

No Fitbit activities logged since 2016-08-23

2016-08-26 / 21:14:42 ♒♒♒  ☺  
```

And this is the screenshot from just now.

![screenshot_2016-08-26-21-16-19-405_com fitbit fitbitmobile](https://cloud.githubusercontent.com/assets/65480/18011426/c2836c04-6bd2-11e6-909c-21d77a659c0c.png)


Do you know why there is this anomaly ?

Fitbit App says it has synced up till 25th 23:59 hrs.

Your app's log say, it synced data up till 26th.

Your app's summary says no Fitbit data after 24th.


So, do you know if Fitbit processes the data, before it makes it available to other parties to use over its public api ?

**Comment by praveendath92** [comment]
Clarification : Fitbit activities are **exercises**

**Comment by praveendath92** [comment]
@rickysarraf , Updated the log output with the clarification. Let me know if it is still misleading. Thanks again!

**Comment by rickysarraf** [comment]
Oh!! That was the cause of the confusion. Now your reporting is inline with what the Fitbit app says.

Thank you.
