### ISSUE TITLE
KeyError: 'activities-steps-intraday'

### ISSUE THREAD

**Issue by fipm** [praveendath92/fitbit-googlefit#8]
Hi, while trying to sync I get this error:

------------------------------   2016-07-23  -------------------------
Traceback (most recent call last):
  File "app.py", line 96, in <module>
    main()
  File "app.py", line 67, in main
    remote.SyncFitbitToGoogleFit('steps',date_stamp)
  File "/home/mook/git/fitbit-googlefit/remote.py", line 125, in SyncFitbitToGoogleFit
    return self.SyncFitbitIntradayToGoogleFit(dataType, date_stamp)
  File "/home/mook/git/fitbit-googlefit/remote.py", line 153, in SyncFitbitIntradayToGoogleFit
    intraday_data = interday_raw[resp_id]['dataset']
KeyError: 'activities-steps-intraday'

**Comment by praveendath92** [comment]
@fipm , Check the discussion from issue #1

**Comment by fipm** [comment]
I see, thanks. For future reference, Fitbit Developer Console seems to default to "server" no matter what you choose initially. I had to change my application type back to "personal" manually after creation to get it to stick.

**Comment by praveendath92** [comment]
@fipm , Didn't notice that during my setup. Thanks for notifying. In any case, I added exception handling in the code to inform the user about this.
