### ISSUE TITLE
KeyError: 'activities-steps-intraday'

### ISSUE THREAD

**Issue by dipietro-salvatore** [praveendath92/fitbit-googlefit#9]
Hello,
I just start to use this project to export the Fitbit data to Google Fit. I installed it and I am trying to export the data for the first time. However, I have this error:

python3 app.py -s "4 days ago" -e tomorrow
------------------------------   2016-08-22  -------------------------
Traceback (most recent call last):
  File "app.py", line 96, in <module>
    main()
  File "app.py", line 67, in main
    remote.SyncFitbitToGoogleFit('steps',date_stamp)
  File "/home/diego/Downloads/fitbit-googlefit/remote.py", line 125, in SyncFitbitToGoogleFit
    return self.SyncFitbitIntradayToGoogleFit(dataType, date_stamp)
  File "/home/diego/Downloads/fitbit-googlefit/remote.py", line 153, in SyncFitbitIntradayToGoogleFit
    intraday_data = interday_raw[resp_id]['dataset']
KeyError: 'activities-steps-intraday'

How can I solve it?
Thank you

**Comment by praveendath92** [comment]
@dipietro-salvatore , This is due to a minor mistake in your Fitbit setup. See [solution](https://github.com/praveendath92/fitbit-googlefit/issues/2#issuecomment-242469390)
